name: test

on:
  pull_request:
    branches: [master]
  push:
    branches: [master]

jobs:
  test-urls:
    name: Test URLs
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        command:
          - test:blog-urls
          - test:docs-urls
          - test:web-urls

    steps:
      - name: Check out Git repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Set up Node.js
        uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8 # v4.0.1
        with:
          node-version: 20
          check-latest: true
          cache: npm

      - name: Build and start test server
        run: |
          npm ci --no-audit
          npm run build
          npm run serve &

      - name: Test URL
        run: npm run ${{ matrix.command }}
